[build]
builder = "railpack/v1"

[phases.install]
workdir = "RNN/backend"
cmds = ["pip install -r requirements.txt"]

[phases.start]
workdir = "RNN/backend"
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[deploy]
restartPolicyType = "ON_FAILURE"
